name: Release & Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Professional Platform
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run full test suite
      run: |
        pip install pytest pytest-cov
        pytest tests/ --cov=modules --cov-report=term -v
    
    - name: Professional validation
      run: |
        python validate_pro_config.py
    
    - name: Create release artifacts
      run: |
        mkdir -p dist
        python -m pip install build
        python -m build
    
    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-dist
        path: dist/
    
    - name: Generate release notes
      run: |
        echo "# Professional Trading Platform Release" > RELEASE_NOTES.md
        echo "## Version: ${{ github.ref_name }}" >> RELEASE_NOTES.md
        echo "## Date: $(date '+%Y-%m-%d')" >> RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        echo "### Professional Features" >> RELEASE_NOTES.md
        echo "- Institutional-grade risk management" >> RELEASE_NOTES.md
        echo "- Real-time signal generation (0-100 scoring)" >> RELEASE_NOTES.md
        echo "- Professional portfolio tracking" >> RELEASE_NOTES.md
        echo "- Advanced backtesting engine" >> RELEASE_NOTES.md
    
    - name: Notify deployment
      run: |
        echo "✅ Professional platform deployed successfully"
